services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  microservice1:
    build: ./microservice1
    ports:
      - "8081:8000"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  microservice2:
    build: ./microservice2
    ports:
      - "8082:7999"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
  
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"